manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main  # 或指定稳定版本如 0.5.0
      import: app/west.yml
  self:
    path: config
