CONFIG_ZMK_KEYBOARD=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y

# 直接用直连按键（不用矩阵，最稳定）
CONFIG_ZMK_KSCAN_DIRECT=y
CONFIG_ZMK_KSCAN_DIRECT_KEY_COUNT=3

# 必须加物理布局
CONFIG_ZMK_PHYSICAL_LAYOUTS=y
CONFIG_ZMK_PHYSICAL_LAYOUT_DEFAULT="L0"
